/**
 * Playlist display component with Spotify-style design
 */

'use client';

import { SpotifyTrack } from '@/lib/spotify-api';
import TrackCard from './TrackCard';
import { shuffleArray } from '@/lib/spotify-utils';
import { useState } from 'react';

interface PlaylistDisplayProps {
  tracks: SpotifyTrack[];
  emotion?: string;
  title?: string;
  onPlayTrack?: (track: SpotifyTrack) => void;
}

export default function PlaylistDisplay({
  tracks,
  emotion,
  title = 'Your Emotion-Based Playlist',
  onPlayTrack,
}: PlaylistDisplayProps) {
  const [shuffledTracks, setShuffledTracks] = useState<SpotifyTrack[]>(tracks);
  const [isShuffled, setIsShuffled] = useState(false);

  const handleShuffle = () => {
    if (isShuffled) {
      setShuffledTracks(tracks);
      setIsShuffled(false);
    } else {
      setShuffledTracks(shuffleArray(tracks));
      setIsShuffled(true);
    }
  };

  const displayTracks = isShuffled ? shuffledTracks : tracks;

  return (
    <div className="w-full">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold text-white">{title}</h2>
          <p className="text-sm text-zinc-400 mt-1">
            {tracks.length} tracks • Generated by EmoRec
          </p>
        </div>

        {/* Controls */}
        <div className="flex gap-3">
          <button
            onClick={handleShuffle}
            className={`
              px-4 py-2 rounded-full font-medium transition-all
              ${
                isShuffled
                  ? 'bg-green-500 text-black hover:bg-green-400'
                  : 'bg-white/10 text-white hover:bg-white/20'
              }
            `}
          >
            🔀 {isShuffled ? 'Unshuffle' : 'Shuffle'}
          </button>
          
          <button
            className="px-6 py-2 rounded-full bg-green-500 text-black font-medium hover:bg-green-400 transition-colors"
          >
            ▶ Play All
          </button>
        </div>
      </div>

      {/* Tracks list */}
      <div className="space-y-1">
        {displayTracks.map((track, index) => (
          <TrackCard
            key={`${track.id}-${index}`}
            track={track}
            index={index}
            emotion={emotion}
            onPlay={onPlayTrack}
          />
        ))}
      </div>
    </div>
  );
}
